# Generated by Django 4.2.6 on 2023-11-01 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecomment',
            name='depth',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='recipecomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='recipes.recipecomment'),
        ),
    ]
